// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAssemblyBlazorDemo.Server.Data;

namespace WebAssemblyBlazorDemo.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebAssemblyBlazorDemo.Shared.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("AnimalKind")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstimatedAge")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalKind = 0,
                            EstimatedAge = 1,
                            Gender = 1,
                            Name = "Max",
                            PictureUrl = "https://cdn.pixabay.com/photo/2017/06/24/09/13/dog-2437110__340.jpg"
                        },
                        new
                        {
                            Id = 2,
                            AnimalKind = 1,
                            DateOfBirth = new DateTime(2018, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 0,
                            Name = "Kitty",
                            PictureUrl = "https://cdn.pixabay.com/photo/2014/04/13/20/49/cat-323262__340.jpg"
                        },
                        new
                        {
                            Id = 3,
                            AnimalKind = 0,
                            EstimatedAge = 2,
                            Gender = 0,
                            Name = "Lucy",
                            PictureUrl = "https://cdn.pixabay.com/photo/2018/03/18/18/06/australian-shepherd-3237735__340.jpg"
                        },
                        new
                        {
                            Id = 4,
                            AnimalKind = 0,
                            EstimatedAge = 3,
                            Gender = 1,
                            Name = "Charlie",
                            PictureUrl = "https://cdn.pixabay.com/photo/2017/10/02/21/56/dog-2810484__340.jpg"
                        },
                        new
                        {
                            Id = 5,
                            AnimalKind = 1,
                            EstimatedAge = 1,
                            Gender = 0,
                            Name = "Simba",
                            PictureUrl = "https://cdn.pixabay.com/photo/2017/11/09/21/41/cat-2934720__340.jpg"
                        },
                        new
                        {
                            Id = 6,
                            AnimalKind = 1,
                            EstimatedAge = 6,
                            Gender = 1,
                            Name = "Sammy",
                            PictureUrl = "https://cdn.pixabay.com/photo/2017/03/14/14/49/cat-2143332__340.jpg"
                        });
                });

            modelBuilder.Entity("WebAssemblyBlazorDemo.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VatPercentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dogfood",
                            Price = 10.99m,
                            ProductImageUrl = "https://upload.wikimedia.org/wikipedia/commons/4/4f/Hundefutter.jpg",
                            VatPercentage = 21
                        },
                        new
                        {
                            Id = 2,
                            Name = "Catfood",
                            Price = 8.99m,
                            ProductImageUrl = "https://upload.wikimedia.org/wikipedia/commons/1/16/Whiskas_cat%27s_petfood_with_chicken_dry.jpg",
                            VatPercentage = 21
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cat litter 50 liter",
                            Price = 15.12m,
                            ProductImageUrl = "https://www.publicdomainpictures.net/pictures/30000/velka/cat-litter.jpg",
                            VatPercentage = 21
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
